spring:
  application:
    name: ap_backend
  datasource:
    url: ${JDBC_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cache:
    type: redis
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  context-path: /api/v1

elk:
  host: ${ELK_HOST}
  port: ${ELK_PORT}

security:
  jwtSecret: 12345
  jwtExpirationInMs: 28800000